function ICA_data = sn_CETICAdata(visrej)
% Takes input and creates concatenated file of trials
fs = visrej(1).fsample;

ICA_data            = visrej(1); % used as a template for other data
ICA_data.trial      = [];
ICA_data.time       = [];
ICA_data.trial{1}   = horzcat(visrej(1).trial{:},...
                            visrej(2).trial{:},...
                            visrej(3).trial{:},...
                            visrej(4).trial{:});
ICA_data.time{1}    = (1:length(ICA_data.trial{1}))/fs;
ICA_data.sampleinfo = vertcat(visrej(1).sampleinfo,...
                            visrej(2).sampleinfo,...
                            visrej(3).sampleinfo,...
                            visrej(4).sampleinfo);
ICA_data.block      = {'All Data'};